#sdk: "C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rhodes-3.3.2"
sdkversion: "3.3.2"
name: "DRT"
version: 1.0
vendor: "rhomobile"
build: "debug"
bbver: 4.6
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator5.0"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: "com.rhomobile.drt"
  BundleURLScheme: "drt"
wp:
  productid: "11bee3c1-96ca-012f-5051-0dfe92cba45b"
symbian:
  uid: 3795265999
android:
  version: "2.3.3"
extensions:
  - json
  - another-extension
